name: Google Cloud Run CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_JSON }}
          export_default_credentials: true

      - name: Authenticate gcloud account
        run: |
          echo "${{ secrets.GCP_KEY_JSON_BASE64 }}" | base64 --decode > "${{ runner.temp }}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${{ runner.temp }}/gcloud-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Create .env file
        run: |
          echo "OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }}" >> .env
          echo "GCP_DB_HOST=${{ secrets.GCP_DB_HOST }}" >> .env
          echo "GCP_DB_USER=${{ secrets.GCP_DB_USER }}" >> .env
          echo "GCP_DB_PASSWORD=${{ secrets.GCP_DB_PASSWORD }}" >> .env
          echo "GCP_DB_NAME=${{ secrets.GCP_DB_NAME }}" >> .env

      - name: Deploy to Google Cloud
        run: |
          chmod +x ./continuous_deploy.sh
          ./continuous_deploy.sh
